# Generated by Django 4.2.3 on 2023-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default='default.png', null=True, upload_to='post/'),
        ),
    ]
