# Generated by Django 4.2.3 on 2023-07-07 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_post_image_blog_intro_tag_blog_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='intro',
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
