# Generated by Django 4.2.3 on 2023-07-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_intro_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.CharField(default='', max_length=200),
        ),
    ]
